// ============================================================================
// SISTEMA GM · CAPA COMPARTIDA · INVENTARIO (datos demo)
// ============================================================================

export const EQUIPOS = [
  {
    id: 'EQ-101',
    nombre: 'Sillón odontológico completo',
    marca: 'DentalTech',
    modelo: 'DT-900',
    categoria: 'Odontología',
    tipo: 'Equipo Pesado',
    costoUsd: 10400,
    precioUsd: 15900,
    stock: 2,
    transito: 1,
    minStock: 1,
    vendidos12m: 9,
    ficha: {
      garantiaMeses: 24,
      dimensiones: '190 × 80 × 120 cm',
      consumo: '220V · 1200W',
      specs: [
        { label: 'Tapizado', valor: 'Ecocuero antibacterial' },
        { label: 'Movimientos', valor: 'Electromecánicos, 4 memorias' },
        { label: 'Incluye', valor: 'Lámpara LED, escupidera, compresor' },
        { label: 'Instalación', valor: 'Incluida en Tucumán' },
      ],
    },
  },
  {
    id: 'EQ-102',
    nombre: 'Autoclave 12 litros',
    marca: 'SteriLab',
    modelo: 'SL-12',
    categoria: 'Odontología',
    tipo: 'Equipo Pesado',
    costoUsd: 2100,
    precioUsd: 3200,
    stock: 1,
    transito: 0,
    minStock: 2,
    vendidos12m: 14,
    ficha: {
      garantiaMeses: 12,
      dimensiones: '55 × 45 × 40 cm',
      consumo: '220V · 1500W',
      specs: [
        { label: 'Capacidad', valor: '12 litros' },
        { label: 'Ciclos', valor: '4 programas automáticos' },
        { label: 'Certificación', valor: 'ANMAT' },
      ],
    },
  },
  {
    id: 'EQ-103',
    nombre: 'Ecógrafo veterinario portátil',
    marca: 'VetScan',
    modelo: 'VS-Port',
    categoria: 'Veterinaria',
    tipo: 'Equipo Pesado',
    costoUsd: 5600,
    precioUsd: 8400,
    stock: 0,
    transito: 2,
    minStock: 1,
    vendidos12m: 6,
    ficha: {
      garantiaMeses: 18,
      dimensiones: '32 × 26 × 8 cm',
      consumo: 'Batería 4 h · 220V',
      specs: [
        { label: 'Sondas', valor: 'Lineal y convexa incluidas' },
        { label: 'Pantalla', valor: '10" táctil' },
        { label: 'Almacenamiento', valor: '128 GB + exportación USB' },
      ],
    },
  },
  {
    id: 'EQ-104',
    nombre: 'Mesa quirúrgica hidráulica',
    marca: 'VetLine',
    modelo: 'VL-H2',
    categoria: 'Veterinaria',
    tipo: 'Equipo Pesado',
    costoUsd: 3700,
    precioUsd: 5600,
    stock: 3,
    transito: 0,
    minStock: 1,
    vendidos12m: 4,
    ficha: {
      garantiaMeses: 24,
      dimensiones: '120 × 60 × 90 cm',
      consumo: 'Hidráulica manual',
      specs: [
        { label: 'Material', valor: 'Acero inoxidable 304' },
        { label: 'Carga máxima', valor: '120 kg' },
        { label: 'Altura', valor: 'Regulable 70–110 cm' },
      ],
    },
  },
  {
    id: 'EQ-105',
    nombre: 'Rayos X panorámico digital',
    marca: 'ImagenPro',
    modelo: 'IP-Pan',
    categoria: 'Diagnóstico',
    tipo: 'Equipo Pesado',
    costoUsd: 15800,
    precioUsd: 22500,
    stock: 0,
    transito: 1,
    minStock: 1,
    vendidos12m: 2,
    ficha: {
      garantiaMeses: 24,
      dimensiones: '200 × 130 × 90 cm',
      consumo: '220V · 2000W',
      specs: [
        { label: 'Sensor', valor: 'CMOS digital' },
        { label: 'Tiempo de barrido', valor: '13 s' },
        { label: 'Software', valor: 'Licencia perpetua incluida' },
      ],
    },
  },
  {
    id: 'EQ-106',
    nombre: 'Compresor odontológico silencioso',
    marca: 'AirDent',
    modelo: 'AD-50',
    categoria: 'Odontología',
    tipo: 'Equipo Pesado',
    costoUsd: 1150,
    precioUsd: 1800,
    stock: 4,
    transito: 2,
    minStock: 2,
    vendidos12m: 11,
    ficha: {
      garantiaMeses: 12,
      dimensiones: '60 × 40 × 65 cm',
      consumo: '220V · 750W',
      specs: [
        { label: 'Caudal', valor: '50 l/min' },
        { label: 'Ruido', valor: '< 55 dB' },
        { label: 'Tanque', valor: '25 litros' },
      ],
    },
  },
  {
    id: 'CS-201',
    nombre: 'Kit de cirugía descartable',
    marca: 'GM Insumos',
    modelo: 'KIT-CIR',
    categoria: 'Odontología',
    tipo: 'Consumible',
    costoUsd: 48,
    precioUsd: 90,
    stock: 120,
    transito: 60,
    minStock: 40,
    vendidos12m: 480,
    ficha: {
      garantiaMeses: 0,
      dimensiones: 'Caja 30 × 20 × 10 cm',
      consumo: '—',
      specs: [
        { label: 'Contenido', valor: 'Campo, bata, guantes, gasas, aspirador' },
        { label: 'Esterilidad', valor: 'Óxido de etileno' },
        { label: 'Unidades', valor: '10 kits por caja' },
      ],
    },
  },
  {
    id: 'CS-202',
    nombre: 'Lámpara de fotocurado LED',
    marca: 'DentalTech',
    modelo: 'DT-LED',
    categoria: 'Odontología',
    tipo: 'Consumible',
    costoUsd: 780,
    precioUsd: 1250,
    stock: 6,
    transito: 0,
    minStock: 3,
    vendidos12m: 19,
    ficha: {
      garantiaMeses: 12,
      dimensiones: '25 × 5 × 5 cm',
      consumo: 'Batería recargable',
      specs: [
        { label: 'Longitud de onda', valor: '420–480 nm' },
        { label: 'Modos', valor: '3 (rápido, gradual, pulsante)' },
        { label: 'Autonomía', valor: '300 ciclos' },
      ],
    },
  },
];

export default EQUIPOS;
